### ISSUE TITLE
zen.coderdojo.com とその API の調査

### ISSUE THREAD

**Issue by naopontan** [coderdojo-japan/coderdojo.jp#330]
# 背景

#314 からの[派生](https://github.com/coderdojo-japan/coderdojo.jp/issues/314#issuecomment-390856860)です。 

> zen.coderdojo.com とその API の調査
zen.coderdojo.com って何だ？ → 本家っぽい
zen.coderdojo.com にアクセス API に関するリンクが無いか一通り見てみる
見当たらないので zen coderdojo api でググってみる。 https://zen.coderdojo.com/documentation#/api を発見
アカウントがあると情報量が増えそうなのでアカウント作ってみる ← 今ここ
簡単なサンプルと sandbox 的な場所があれば実際に動かしてみたほうが理解早そうだけど、あるかなー？ って感じで調査中

----

Zen アカウントの方で [アクティブ状態を持っているらしい](https://github.com/coderdojo-japan/coderdojo.jp/issues/310#issuecomment-376125789)ので、API 連携し負担軽減を目指したい。

例えば「一時的に Dojoが休止となった場合、Dojo管理者が Zen 上でステータスを非アクティブにすれば、 coderdojo.jp でも即反映される」と中間の手間が省けて嬉しい。

上記も含めて実現可能かを調査する。

# 関連issue

#314
#310

# TODO

- [x] API に関する guide や reference が無いか調査
- [x] アクティブ/非アクティブの取得APIが用意されているか？の確認
  - [x] zen.coderdojo.com のアカウント作成 & 道場作成
- [x] 用意されているのであれば、実際に動かして確認する
- [x] 用意されていなければ、APIとしてはどんな機能が用意されているのか？を軽くレポートする
- [x] coderdojo.jp のDBに Zen の情報を取り込む時、どんなアプローチがあるか? をいくつかまとめる

**Comment by naopontan** [comment]
初めて issue 立てたけど、こんな感じで良いのかしら...

**Comment by naopontan** [comment]
まずは 「Dojo管理者としてアクティブ/非アクティブの操作」をしてみたいが、テスト環境みたいなのはあるのだろうか?... 🤔

もし、無いとしたら実際にDojo管理者として登録して、登録時のコメント欄に「API連携のテストしたいので、登録しちゃいますー」的な事を書けば良いのか... 🤔

**Comment by naopontan** [comment]
https://zen.coderdojo.com/documentation#/ を眺めてると
`id`, `userId`, `dojoId` などが登場してくる。各々の意味と、具体的な値が知りたいなー。
さて、どうしよう 🤔 
ま、もうちょっと眺めてみる。

....

個人アカウント作ったので userId と思われる値で試しにコールしてみる。

`$ curl -X GET --header 'Accept: application/json' 'https://zen.coderdojo.com/api/2.0/badges/user/35307958-77da-41da-af7b-afd4cdbf6bbd'
{"statusCode":401,"error":"Unauthorized","message":"Missing authentication"}`

認証が必要っぽい。 API で認証か、、、この辺よく分かってないので調査続行。

**Comment by naopontan** [comment]
API Document のページがシンプルすぎてどうやっていいのかわからない。少し手詰まり感が出てきた。
色々とググっても有益な情報を発見できず 😿 

https://zen.coderdojo.com/documentation#!/api/getApi20Countries
のサンプルは手元で実行できた。

他にも以下などは認証不要で実行できた。
- https://zen.coderdojo.com/documentation#!/api/getApi20CountriesContinentsCodes
- https://zen.coderdojo.com/documentation#!/api/getApi20CountriesLatlong


https://zen.coderdojo.com/documentation#!/api/postApi20CountriesPlaces
を試してみるも Internal Server Error なのでサーバ側の問題なのでは...それともパラメータが悪いのかなぁ

```
$ curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
>   "search": {
>     "countryCode": "AS",
>     "search": "okinawa"
>   }
> }' 'https://zen.coderdojo.com/api/2.0/countries/places'
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}[
```

`countryCode` は他にも `JP` って入れたりしたけど変わらず、色々試して２文字ってのは判明した
↓
```
$ curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
  "search": {
    "countryCode": "392",
    "search": "okinawa"
  }
}' 'https://zen.coderdojo.com/api/2.0/countries/places'
{"statusCode":400,"error":"Bad Request","message":"child \"search\" fails because [child \"countryCode\" fails because [\"countryCode\" length must be 2 characters long]]","validation":{"source":"payload","keys":["search.countryCode"]}}
```

こんな手探り状態だと、埒があかないなー。

**Comment by yasulab** [comment]
CoderDojo Foundation が運営する CoderDojo Global Slack があり、その中に `#zen` チャンネルというものがあるのですが、そのチャンネルには CoderDojo Zen の開発者がいるので、そこで直接開発者に質問することはできそうです! 📮 🏃💨

CoderDojo Global Slack
https://coderdojo.com/coderdojo-global-slack/

**Comment by naopontan** [comment]
ありがとうございます 😀  Slack も登録してみます。
今は WebAPI の勉強をしたり  https://forums.coderdojo.com/topic/123/api を眺めたりしてました。

... 英語ですね 🇺🇸  いつもならここで怯むのですが、頑張って進んでみます

**Comment by yasulab** [comment]
うーん、でもアレですね。確かに `Dojos/:id` に適当に入れても返ってこないし、search してみても

```
{
  "statusCode": 403,
  "error": "Forbidden",
  "message": "Forbidden"
}
```

が返って来て、なんか挙動がおかしそうですね🤔💭

**Comment by naopontan** [comment]
はい。今日の件は整理しておきます。
朝会後、オッケーです 🙆

**Comment by yasulab** [comment]
はい! では明日また! お疲れ様でした〜 😆 ♨️ ✨

**Comment by nalabjp** [comment]
昨日ちょっと触ってみて、日本のdojo一覧と思われるレスポンスは取れることが分かったので後で詳細コメントしますね😉

**Comment by naopontan** [comment]
nalabjp さん、ありがとうござます。

----

今は、仮の道場を登録する場面で、どうしても「会場の詳細」が OK になってくれないので、問い合わせを投げようかと準備中です。
（「会場の詳細」で全ての項目を入力しているのに、なんでだろ 💭 ）

**Comment by naopontan** [comment]
拙い英語で問い合わせフォームから質問投げました。
とりあえず作成中の道場は `Pending applications` と表示されています。
このステータスが取れれば良いはずので、調査進めます。

**Comment by nalabjp** [comment]
@naopontan 
https://zen.coderdojo.com/documentation#!/api/postApi20CountriesPlaces
:point_up_2:のAPIが正常なのかどうかはわからないんですが、
日本で登録されているdojoの一覧らしきものは:point_down:のAPIでそれっぽいのが取れました。
https://zen.coderdojo.com/documentation#!/api/postApi20Dojos

パラメータを指定しないと全件取得するっぽい（かなり遅い）んですが、
パラメータに以下を指定すると日本だけに絞り込めていそうです。
```
{
  "query": {
    "countryName": "Japan"
  }
}
```

レスポンスを全て精査したわけではないので、そのあたりの確認はお願いできればと思います。

**Comment by yasulab** [comment]
お、たぶん `stage` っぽい?

## 取得パラメータのサンプル

```
  {
    "entity$": "-/cd/dojos",
    "id": "3a1ef147-d9e7-4398-8c36-7ddf7036e343",
    "mysqlDojoId": null,
    "dojoLeadId": "697c1745-e2ea-4ea7-982f-81852a731275",
    "name": "Maebashi, Gunma",
    "creator": "25cc9c31-eff5-4f9e-92ae-cb87702165c5",
    "created": "2016-10-09T02:16:00.263Z",
    "verifiedAt": "2016-10-17T13:08:18.974Z",
    "verifiedBy": "d22d7ac3-acaf-4ba3-a467-cdf337ef4bc1",
    "verified": 1,
    "needMentors": 1,
    "stage": 3,                 # <== これかな? 🤔💭
    "mailingList": 0,
    "alternativeFrequency": "first",
    "country": {
      "countryName": "Japan",
      "countryNumber": 392,
      "continent": "AS",
      "alpha2": "JP",
      "alpha3": "JPN"
    },
    "county": {},
    "state": {},
    "city": {},
    "place": {
      "nameWithHierarchy": "Maebashi, Gunma Prefecture"
    },
    "coordinates": "36.362198485216354, 139.12779092788696",
    "geoPoint": {
      "lat": 36.3813523,
      "lon": 139.0725053
    },
    "notes": "<p>Suggested Notes:<br />\n<br />\nPlease bring:</p>\n\n<ul>\n\t<li>A pack lunch.</li>\n\t<li>A laptop. Borrow one from somebody if needs be.</li>\n\t<li><strong>A parent! (Very important). If you are 12 or under, your parent must stay with you during the session.</strong></li>\n</ul>\n\n<p> </p>\n",
    "email": "maebashi.jp@coderdojo.com",
    "website": "https://vtmacs003b.github.io/maebashi.jp/",
    "twitter": null,
    "googleGroup": null,
    "supporterImage": null,
    "deleted": 0,
    "deletedBy": null,
    "deletedAt": null,
    "private": 0,
    "urlSlug": "jp/maebashi-gunma-prefecture/maebashi-gunma",
    "continent": "AS",
    "alpha2": "JP",
    "alpha3": "JPN",
    "address1": "3-35, minamicho",
    "address2": null,
    "countryNumber": 392,
    "countryName": "Japan",
    "admin1Code": null,
    "admin1Name": null,
    "admin2Code": null,
    "admin2Name": null,
    "admin3Code": null,
    "admin3Name": null,
    "admin4Code": null,
    "admin4Name": null,
    "placeGeonameId": null,
    "placeName": "Maebashi, Gunma Prefecture",
    "userInvites": null,
    "creatorEmail": "vtmacs003b@gmail.com",
    "taoVerified": 0,
    "expectedAttendees": null,
    "facebook": null,
    "day": 7,
    "startTime": "10:00:00",
    "endTime": "12:00:00",
    "frequency": "1/m"
  },
```

**Comment by naopontan** [comment]
@nalabjp ありがとうございます。私の手元でも確認できました。
@yasulab `stage`が該当するかどうかも含めて調査進めますね。

以下は先程登録した実験用の dojo 情報です。
作成途中なので pending 中です。 以下の値では stage は 0 になってます。

```
{"entity$"=>"-/cd/dojos",
 "id"=>"3d56b7c0-4db6-43cb-81e7-e6d554ee3012",
 "mysqlDojoId"=>nil,
 "dojoLeadId"=>"85d5d9a8-85fa-4d48-8e98-5ceaffb72878",
 "name"=>"sobe-test",
 "creator"=>"35307958-77da-41da-af7b-afd4cdbf6bbd",
 "created"=>nil,
 "verifiedAt"=>nil,
 "verifiedBy"=>nil,
 "verified"=>0,
 "needMentors"=>0,
 "stage"=>0,       # <= ここではゼロですね。pending は 0 ?  🤔💭
 "mailingList"=>0,
 "alternativeFrequency"=>"Occasionally",
 "country"=>
  {"countryName"=>"Japan",
   "continent"=>"AS",
   "alpha2"=>"JP",
   "alpha3"=>"JPN",
   "countryNumber"=>"392"},
 "county"=>nil,
 "state"=>nil,
 "city"=>nil,
 "place"=>nil,
 "coordinates"=>"{\"26.206813496187387\",\"127.69301891326904\"}",
 "geoPoint"=>{"lat"=>26.206813496187387, "lon"=>127.69301891326904},
... 以下、省略 ...
```

`stage` の値でグループ分けすれば何かしら見えてきそうです。
(stage じゃなければ他のフィールドに当たりつけてみます)

**Comment by yasulab** [comment]
> # <= ここではゼロですね。pending は 0 ?  🤔💭

pending は ` "verified"=>0,` っぽいですね。上記の CoderDojo 前橋のサンプルだと `1` になっていたので ✅

**Comment by yasulab** [comment]
CoderDojo Okinawa の stage ってどうなってますかね? `1` ですかね? 👀 
https://zen.coderdojo.com/dojos/jp/okinawa-ken/okinawa-okinawa-prefecture/okinawa

<img width="265" alt="screen shot 2018-05-23 at 15 12 16" src="https://user-images.githubusercontent.com/155807/40406500-df959070-5e9b-11e8-821f-443b4fcaa175.png">

**Comment by naopontan** [comment]
私の権限では見れないようです。

zen 上では私は関わっていない状態でした (><)
「メンターとして」ボタンを押して関係性を持ったのですが、それでも ↑ の画面は見えないです 😓

**Comment by naopontan** [comment]
もしかしたら「チャンピオンとして参加」ボタンを押せば画面が見えるようになるかもしれませんが、本当のチャンピオンのお断りとかが必要かと。

**Comment by naopontan** [comment]
ゼロになってます...

```
  "name"=>"Haebaru at artisan",
  "creator"=>"8b7b4bd8-0e84-49c2-ac5a-a1a01cc85908",
  "created"=>"2016-11-18T02:15:11.458Z",
  "verifiedAt"=>"2016-11-22T14:16:55.476Z",
  "verifiedBy"=>"9c9ed75a-660f-4a2e-a92e-f267c161c34d",
  "verified"=>1,
  "needMentors"=>1,
  "stage"=>0,
```

**Comment by naopontan** [comment]
只今、データを眺めるスクリプト書いてます 📝

**Comment by yasulab** [comment]
> "stage"=>0,

なるほどなるほど。少なくとも 0〜3以上の４種類以上の状態が保存されることが分かったので、恐らく `stage: 4` という状態もありそうですね🤔CoderDojo 西成が既に非アクティブな状態にしているかどうかは未確認ですが、現状の CoderDojo 西成の stage の値も気になってきますね 👀

**Comment by yasulab** [comment]
> {:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"Sendai"}
> {:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"Asahikawa City"}

お、これは非アクティブな Dojo なので coderdojo.jp からも非表示になっている Dojo なんですよね。ということは `stage: 4` が「非アクティブ」という認識で合っていそうです 👀

**Comment by naopontan** [comment]
```
[naopontan@naopontan-MBP coderdojo.jp]$ ruby hoge.rb | grep "stage=>4"
{:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"SapporoEast"}
{:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"Kotesashi @ Do it"}
{:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"Fukuyama,Hiroshima"}
{:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"CoderDojo Kagoshima（CoderDojo鹿児島）"}
{:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"Shiroisi"}
{:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"Okayama"}
{:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"Azumino"}
{:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"Okayama"}
{:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"Sendai"}
{:verified=>1, :stage=>4, :deleted=>0, :taoVerified=>0, :name=>"Asahikawa City"}
[naopontan@naopontan-MBP coderdojo.jp]$
[naopontan@naopontan-MBP coderdojo.jp]$ ruby hoge.rb | grep "stage=>4" | wc -l
      10
```

stage: 4 なデータは 10 個あるようです。
これで合っている。で仕様を決めて(も)良いでしょうか？

**Comment by naopontan** [comment]
すみません、言葉たらずだったかも。補足です。
考えが細かいかもしれませんが、「stage が 4 は非アクティブだ」と仕様を決めつけるラインをどこに持っていったらいいのかわからないので 🙏 💦 
運営していて各道場の動きがある程度分かっていて経験則から、ほぼ間違いないの判断なのか、それともステータスを変更する画面の html を見て、フィールド名が `stage` となっていたら良しとするのか、、、ソースコードまで確認しに行くのか？、、、などなどです。

その辺りの感覚を知りたくて... 😅

**Comment by yasulab** [comment]
> stage が 4 は非アクティブ

札幌東と安曇野が `stage: 4` になっている点は気になりますが、他の CoderDojo は現在非アクティブであることはそれぞれの Dojo 情報を個別に調べてみれば確認できるかなと思います ✅また、基本的に非アクティブな Dojo は coderdojo.jp のトップページからも非表示になっているはずです 🔧 💨  ただし、ここは @yasulab が手動で対応しているので、漏れがある可能性はあります 🙈💦 

> ほぼ間違いないの判断なのか、それともステータスを変更する画面の html を見て、フィールド名が stage となっていたら良しとするのか、、、zen のソースコードまで確認しに行くのか？

はい、「ほぼ」間違いないという判断ですが、「ほぼ」を「確実」にしたい場合は、CoderDojo Global Slack で開発者に `stage` の意味について確認をとることもできそうですね 🌏

**Comment by yasulab** [comment]
工数見積りや仕様策定、より正しい開発方針の模索のために必要な情報があれば、お気軽に聞いてもらえれば!  😸✨

**Comment by nalabjp** [comment]
Okayamaが2つあるのがちょっと気になったので調べてみたら`"name":"Okayama"`なdojoは3つあるんですねぇ。
残りの一つはstageが1でした。
OkayamaDojoを名乗るところが3回登録されているってことなんですかねぇ？🤔

**Comment by yasulab** [comment]
> "name":"Okayama"なdojoは3つある

2012~2013年ごろに Okayama が1つ合ったのは覚えているので、3つのうち１つはそれですね。いま活発なのは [岡山 岡南](https://www.coderdojo-konan.jp/) がもう1つで、最後の1つは気になりますね🤔💭

間違って2つ Dojo を作ってしまったケースは何度か見かけたことがあるので、もしかしたらそういったケースの1つかもしれません 😅

**Comment by naopontan** [comment]
https://github.com/coderdojo-japan/coderdojo.jp/issues/330#issuecomment-391232303 の画面を見ると
- In planning
- Open, come along
- Register ahead
- フルアップ
- 非アクティブ

と5つあり、以下のstage の種類と一致しますね。

配列の先頭がステータスコードで、2番めが道場数です。
↓
```
stage
[0, 66]
[1, 116]
[2, 10]
[3, 14]
[4, 10]
```

coderdojo.jp の登録数が 140 なので、ステータスの 1, 2, 3 を足すと 116 + 10 + 14 でピッタリ 140
うーん、、、これでいいのかなぁ。また明日、調査続けます。

**Comment by naopontan** [comment]
**「zen に存在する道場は必ず jp サイトにも存在する」** は成り立たない...ですよね！？
おそらく、別々で管理されているので片方がなかったり、あっても情報が異なっている場合があるのかなーと。
この認識はあっていますか？ 🤔

**Comment by yasulab** [comment]
はい、それは成り立たないですね。登録してからすぐに開催できる Dojo はほとんどなく、ある程度準備ができた段階で申請していただくフローになります💨

**Comment by naopontan** [comment]
zen と jp側の道場の紐付けをどうするかですね 🤔 
パッと考えると dojos テーブルに zen 側の dojo_id を持たせる感じかなー ... 💭

あと、zen と jp側の道場の各々の情報(DBフィールド)で被りとかが無いかも気になります。
見比べてみて頭に入れてみます。

**Comment by yasulab** [comment]
はい! 今回は Japan から Zen の情報を部分定期にでも取得する仕組みについて調べられれば十分ですので、実際の実装は後回しもしくは別 Issue が良いかなと考えています 😸 Description の方にも次の内容を書き足しておきました 📝 

> - [ ] coderdojo.jp に Zen の情報を部分的に取り込むとき、どんなアプローチがあるか? をいくつかまとめる

☝️ ここまで達成したら、今回の API 調査は一旦完了としましょう ✅ 

まとめられたアプローチを協議して、もし簡単に実現できそうであれば API 連携で非アクティブを実装しても良いですし、もし難しそうであれば代替案の Suspension モデルでも良さそうです (もしくは別案が思い付けばそれも歓迎です! 😄)

API を通した Zen/Japan 間のシステム連携はいずれやりたいと思っていたので、もし今回 API 連携のアプローチを採らなかったとしても、今回の API 調査の結果は今後の事例で役に立つかなと目論んでいます 💭 ✨

**Comment by naopontan** [comment]
↑了解しました。

せっかくなので、先程調査した情報を↓に貼り付けておきますね。
（コメント書いている途中だった）

----
宜野湾道場をサンプルとして比較してみます。

# zen の情報

```
{
  "entity$": "-/cd/dojos",
  "id": "901f6e5c-f3de-4bb6-9279-825505872b41",
  "mysqlDojoId": null,
  "dojoLeadId": "fff55e7e-6c5a-42a7-85ed-d4335fb19841",
  "name": "Ginowan, Okinawa@ Okigin S.P.O",
  "creator": "8ffd8c09-f254-4635-b0ce-9db02f64479a",
  "created": "2017-09-20T17:01:33.159Z",
  "verifiedAt": "2017-09-20T17:01:44.091Z",
  "verifiedBy": "d22d7ac3-acaf-4ba3-a467-cdf337ef4bc1",
  "verified": 1,
  "needMentors": 0,
  "stage": 1,
  "mailingList": 0,
  "alternativeFrequency": null,
  "country": {
    "countryName": "Japan",
    "continent": "AS",
    "alpha2": "JP",
    "alpha3": "JPN",
    "countryNumber": "392"
  },
  "county": null,
  "state": null,
  "city": null,
  "place": {
    "nameWithHierarchy": "日本沖縄県宜野湾市"
  },
  "coordinates": "{\"26.2695532\",\"127.73904620000008\"}",
  "geoPoint": {
    "lat": 26.269556,
    "lon": 127.73904100000004
  },
  "notes": "<ul>\n\t<li>場所：沖縄県宜野湾市真志喜１丁目１３−１６（株式会社おきぎんエス・ピー・オー2階会議室）</li>\n\t<li>費用：無料</li>\n\t<li>資格：7歳から17歳</li>\n\t<li>定員：10名</li>\n\t<li>持物：自分のパソコンがあれば持参して下さい。無い場合は道場のパソコンを利用することも可能ですが台数に限りが有るため、全員に行き渡らない可能性があります。<br />\n\t※作ったプログラムや作品を継続して保存したい場合、自宅でも学習したい場合はパソコンを持参することをオススメします。</li>\n\t<li>通常の日程：\n\t<ul>\n\t\t<li>9:00 - 9:30：初めての方向けDojoの説明</li>\n\t\t<li>9:30 - 11:30：プログラミング</li>\n\t\t<li>11:30 - 12:00：発表</li>\n\t\t<li>12:00 - 12:30：Dojo日記の記入と片付け</li>\n\t</ul>\n\t</li>\n\t<li>内容：\n\t<ul>\n\t\t<li>初心者向け：Scratch（スクラッチ）プログラミング</li>\n\t\t<li>中級者向け：ロボット初級プログラミング<br />\n\t\t※上級者向けメニューは準備中です。もう少々お待ち下さい。</li>\n\t</ul>\n\t</li>\n</ul>\n",
  "email": "coderdojo.ginowan@gmail.com",
  "website": "http://www.coderdojo-ginowan.com/",
  "twitter": "coderdojogwan",
  "googleGroup": null,
  "supporterImage": null,
  "deleted": 0,
  "deletedBy": null,
  "deletedAt": null,
  "private": 0,
  "urlSlug": "jp/ri4-ben3-chong1-sheng2-xian4-yi2-ye3-wan1-shi4/ginowan-okinawa-okigin-s-p-o",
  "continent": "AS",
  "alpha2": "JP",
  "alpha3": "JPN",
  "address1": "真志喜1-13-16（株式会社おきぎんエス・ピー・オー2階会議室）",
  "address2": null,
  "countryNumber": 392,
  "countryName": "Japan",
  "admin1Code": null,
  "admin1Name": null,
  "admin2Code": null,
  "admin2Name": null,
  "admin3Code": null,
  "admin3Name": null,
  "admin4Code": null,
  "admin4Name": null,
  "placeGeonameId": null,
  "placeName": "日本沖縄県宜野湾市",
  "userInvites": [

  ],
  "creatorEmail": "yama555net@gmail.com",
  "taoVerified": 0,
  "expectedAttendees": 10,
  "facebook": "coderdojo.ginowan",
  "day": 6,
  "startTime": "09:30:00",
  "endTime": "12:30:00",
  "frequency": "1/w"
}
```

# coderdojo.jp の情報

```
=> [#<Dojo:0x00007fed48d39a40
  id: 106,
  name: "宜野湾 (沖縄)",
  email: "",
  order: "472051",
  description: "沖縄県宜野湾市で不定期開催",
  logo: "/img/dojos/ginowan.png",
  url: "http://www.coderdojo-ginowan.com/",
  tags: ["Scratch", "C-Style", "Mindstorm", "Java", "Swift"],
  created_at: Thu, 17 May 2018 10:47:02 JST +09:00,
  updated_at: Thu, 17 May 2018 10:47:02 JST +09:00,
  prefecture_id: 47>]
[4] pry(main)>
```

**Comment by naopontan** [comment]
>  coderdojo.jp に Zen の情報を部分的に取り込むとき、どんなアプローチがあるか? をいくつかまとめる

- jp のフィールドで似たようなのは zen にあるか？
  - `name` は名前は同じだけど、jp は日本語、zen は英語で入ってたりする
  - `email` は **同じ情報** として良いはずだ
  - `description` は ... うーん、、今のところ不明としときます
  - `logo` は... zen には無いっぽい
  - `url` は `website` と同一情報
  - `tags` は持ってないっぽい

「Zenの情報を部分的に取り込むアプローチは...」の前に「道場の情報は zen と jp のどちらで修正するの？」があると思います。

- zen 側で全て済ませる → これは jp 固有の情報を既に持っているので難しそう
- jp 側で全て済ませる → zen 側の情報をAPI経由で更新する → APIを駆使＆機能あるか？の要調査

現状だと

1. zen で登録して道場開設
2. jp で登録してjp サイト掲載
3. jp がメイン的な扱い（！？）になっているのでメンテが発生したら dojos.yaml を修正
  3.1. 気づいている人は zen 側の情報も更新

という感じだと思います。

... 引き続き、もうちょっと考えます ...

**Comment by naopontan** [comment]
https://github.com/coderdojo-japan/coderdojo.jp/issues/330#issuecomment-391220996
の問い合わせの回答が来ました。

> We were we experiencing some technical issues this morning with the 'Start a Dojo' application form. The issue has been resolved now, so please try again. Hopefully it will work this time :)

今、登録したら出来ました。
（市町村のフィールドで `naha` を入力しても候補が出てこない不具合だった）

これで道場の情報がいじれる 😸

**Comment by yasulab** [comment]
> アプローチとしては「zen にしか無い情報は zen 上で修正させる」がいいと思います

こちら、アプローチとしては「zen にしか無い情報は zen 上で修正させる」以外の方法はない、という認識で大丈夫ですか? 🤔💭

タスクとして書き出していた、

>  coderdojo.jp のDBに Zen の情報を取り込む時、どんなアプローチがあるか? をいくつかまとめる

に対して、この Issue が Close された時点までに出てきたアプローチが１つしかなかったので 😅

**Comment by yasulab** [comment]
> jp 側で全て済ませる → zen 側の情報をAPI経由で更新する → APIを駆使＆機能あるか？の要調査

あ、こちらも別案として1つありましたね。これを足して2つのアプローチがある、ということですかね🤔

**Comment by yasulab** [comment]
もうちょっと具体的な参考情報を出すと、API 連携の調査結果が他に人から見ても役に立つように、例えば次のような形で情報をまとめてもらえると嬉しいです 🙏 こちらもご参考にしていただければ! 😸 

- [Railsガイドを差分検知できる状態にするためにやること](https://yasslab.qiita.com/shared/items/f4ef51f4e5616313c06d)
- [Railsガイドのフィジビリティスタディメモ](https://yasslab.qiita.com/shared/items/216721e5737ccb90a3f6)
- [Railsガイドのプロトタイプ開発](https://yasslab.qiita.com/shared/items/83573409e6d0b43d2e2e)

⚠️ タイトルに社内の秘密情報が含まれているため一部タイトルを変えています

**Comment by naopontan** [comment]
>> アプローチとしては「zen にしか無い情報は zen 上で修正させる」がいいと思います
>
> こちら、アプローチとしては「zen にしか無い情報は zen 上で修正させる」以外の方法はない、という認識で大丈夫ですか? 🤔💭

と

>> jp 側で全て済ませる → zen 側の情報をAPI経由で更新する → APIを駆使＆機能あるか？の要調査
>
> あ、こちらも別案として1つありましたね。これを足して2つのアプローチがある、ということですかね🤔

はそういう意味では1つですね 😅 
そっか、他のアプローチは...うーん、すみません思いつかない.. 😿 

----
> もうちょっと具体的な参考情報を出すと、API 連携の調査結果が他に人から見ても役に立つように、例えば次のような形で情報をまとめてもらえると嬉しいです

@yasulab 
こちらは Qiita:Team の方でまとめた方がいいですか？それとも、この issue 上のコメントとしてまとめる。って事でしょうか？

**Comment by yasulab** [comment]
恐らく記事内容を何度か修正・変更することになりそうなので、まずは Qiita:Team で書いてもらって、内容が固まってきたらこちらの Description に転記するカタチで行きましょう! 👍 (なので基本的には一般公開する前提で書いてもらえれば 📝 💨 )

**Comment by yasulab** [comment]
> 本 Issue の Description に転記する

@naopontan こちら、そういえば [/docs](https://github.com/coderdojo-japan/coderdojo.jp/tree/master/docs) ディレクトリがあったことを失念していました >< 💦 

Issue の Description より docs ディレクトリの方が読まれやすいので、調査結果をまとめたレポートを docs ディレクトリに置いたら本 Issue を完了としましょう ✨📑📝

cf. ドキュメント例: [新規Dojoの追加方法](https://github.com/coderdojo-japan/coderdojo.jp/blob/master/docs/how-to-add-dojo.md)

**Comment by naopontan** [comment]
@yasulab 
確認ですが、 Qiita:Team に先程POSTした情報を Markdown 形式で /docs 配下に新規で作れば良いですか？

**Comment by yasulab** [comment]
はい! そちらでよろしくお願いします ;) いくつかフィードバックしたい部分もあるので、PRで出していただけると助かります 📑👀
