### ISSUE TITLE
Upgrade Rails 5.1.7 to Rails 5.2.x 

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#364]
## Past PRs

- Upgrade Rails and Scrivito gems to the latest #163
- Upgrade to Ruby 2.4.0, Rails 5.0.1, and Scrivito 1.7.0 #94

## We will
(`WIP` will be removed when the following items are checked. ✅)

- [x] #366 Delete fixed gem: faraday_middleware v0.10 
- [x] #366 Upgrade Scrivito to [1.4.0](https://www.scrivito.com/scrivito-rails-sdk-1-14-0-has-been-released-ee19a75f73f84eb8) to [1.5.0](https://www.scrivito.com/scrivito-rails-sdk-1-15-0-has-been-released-ec8beff7b46d4660)
- [ ] #704 Upgrade Scrivito to [1.16.0](https://www.scrivito.com/scrivito-rails-1-16-0-released-rails-5-2-support-and-improved-link-editor-677d40b3d66e977d) (Rails 5.2 Support)
- [ ] #704 Upgrade Rails to [5.2.2](https://railsguides.jp/5_2_release_notes.html)
   - Can't upgrade to Rails 5.2.x before upgrading Scrivito Rails SDK.

### Current Status

```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 5.2.2)

    scrivito (~> 1.13.0) was resolved to 1.13.0, which depends on
      scrivito_sdk (= 1.13.0) was resolved to 1.13.0, which depends on
        rails (< 5.2, >= 4.2)
```

~~Waiting @Scrivito Rails SDK to be available with Rails 5.2.x or higher. 🙏~~ 

**Now Scrivito becomes ready for upgrading Rails!!** 😎🆒✨ => #704

**Comment by yasulab** [comment]
Oops, we need to wait for @Scrivito Rails SDK to be available with Rails 5.2.x or higher. 💦 

```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 5.2.2)

    scrivito (~> 1.15.0) was resolved to 1.15.0, which depends on
      scrivito_sdk (= 1.15.0) was resolved to 1.15.0, which depends on
        rails (< 5.2, >= 4.2)
```

cf. Scrivito Rails SDK 1.15.0 Has Been Released
https://www.scrivito.com/scrivito-rails-sdk-1-15-0-has-been-released-ec8beff7b46d4660

**Comment by yasulab** [comment]
MEMO: Tiny upgrade from 5.1.6 -> 5.1.6.2 by this PR: #402

**Comment by yasulab** [comment]
> ### Current Status
> Waiting Scrivito Rails SDK to be available with Rails 5.2.x or higher. 🙏

It seems we are ready to upgrade....!! 🚀🆕✨ 

📜Scrivito Rails 1.16.0 Released - Rails 5.2 Support & Improved Link Editor
https://www.scrivito.com/scrivito-rails-1-16-0-released-rails-5-2-support-and-improved-link-editor-677d40b3d66e977d

**Comment by yasulab** [comment]
公式ドキュメントしか情報が無さそうなので (ググっても恐らく公式ドキュメント以外には何も情報出て来なさそうなので) 結構難しいタスクだと思いますが、もし興味あればぜひ ;) cc/ @Yuppymam

**Comment by kimihito** [comment]
https://github.com/coderdojo-japan/coderdojo.jp/pull/535 で 5.1.7が `master` になったのでタイトルを変更しました
