### ISSUE TITLE
Rails 5.2 から Rails 6.0+ にアップグレードする

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#736]
Rails 6.0 系に上げたら、Ruby のバージョンを 2.6.x から 2.7.0 に上げる。

## Todo

- [ ] Upgrade Scrivito SDK that supports Rails 6.0 (Currently no support :sob: )
   - cf. https://www.scrivito.com/rails/release-notes
- [ ] Upgrade Rails version from 5.2 to 6.0
   - cf. https://railsguides.jp/upgrading_ruby_on_rails.html
- [ ] Upgrade Ruby version from 2.6. to 2.7
   - cf. http://koic.hatenablog.com/entry/towards-ruby-3-0-with-rails-ecosystem
   - cf. https://tech.recruit-mp.co.jp/server-side/post-19932/

## Past PRs

- [x] #94 Upgrade to Ruby 2.4.0, Rails 5.0.1, and Scrivito 1.7.0
- [x] #163 Upgrade Rails and Scrivito gems to [1.16.0](https://www.scrivito.com/scrivito-rails-1-16-0-released-rails-5-2-support-and-improved-link-editor-677d40b3d66e977d)
- [x] #704 Upgrade Rails: 5.1.7 -> 5.2.4.1 (cf. #364)
- [x] #949 Upgrade Rails and Scrivito gems to [1.17.0](https://www.scrivito.com/scrivito-rails-1-17-0-released-79afa2ec5eff3347)
- [x] ~~#950 Exec: `bundle update`~~ (Need to tweak asset files before updating)
- [x] Update Ruby version: 2.6.5 -> 2.7.1 (Log: #735, blocked by Scrivito gems)

**Comment by yasulab** [comment]
Status updated! :up: ✨

**Comment by yasulab** [comment]
Scrivito SDK v1.18.0 がリリースされた！が...、どうやら Rails 6 をスキップしているようなのでかなり難しそう...💦 (担当チームから許諾ももらっているので一旦 #1388 を進めた方が良いかも?)

Scrivito for Rails SDK 1.18.0 Released
https://www.scrivito.com/scrivito-for-rails-sdk-1-18-0-released-c68c2b56f1bfbdbe

> Earlier Rails versions are no longer supported by Scrivito. Note that during the upgrade **you will need to migrate from Rails 5.2 (with Scrivito 1.17.0) directly to Rails 7.0 (with Scrivito 1.18.0).**

```
$ bundle update scrivito
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.2)

    scrivito (~> 1.18) was resolved to 1.18.0, which depends on
      scrivito_sdk (= 1.18.0) was resolved to 1.18.0, which depends on
        rails (~> 7.0.0)
```

**Comment by nanophate** [comment]
Rails 6.x にアップグレードしたのと #1541 と #1268  #1506 で scrivito 関連の Gem を削除したので、クローズします。
